/**
 * Products REST API
 * RESTful API for Products
 *
 * OpenAPI spec version: 1.0
 * Contact: rafaeldblima@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Category } from './category';


export interface Product {
    categoria?: Category;
    dataCompra?: Date;
    descricao?: string;
    id?: number;
    origem?: string;
    preco?: number;
}
